### ISSUE TITLE
Please add a dark theme

### ISSUE THREAD

**Issue by vitaly-zdanevich** [portagefilelist/server#44]
Utilizing https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by bananas-repos** [comment]
@vitaly-zdanevich 
Thank you for your feedback. I've transfered the issue to the correct repository.

The current ui framework does not support a dark theme out if the box, but has ways to implement it. So no quick fix, but I will work on it.

**Comment by bananas-repos** [comment]
@vitaly-zdanevich I've added the dark mode. Was faster than I thought. Can you please have a look and try it at your end?

Thx.

**Comment by vitaly-zdanevich** [comment]
Wow, thanks.

This red is a little difficult to read
![image](https://github.com/user-attachments/assets/ac8ac496-d034-42f9-b4d5-6758e3be0230)

**Comment by bananas-repos** [comment]
Thank you for the feedback. 

I've altered the color. Please check.

**Comment by vitaly-zdanevich** [comment]
Great, thanks :)

**Comment by bananas-repos** [comment]
Thank you!

**Comment by bananas-repos** [comment]
Close
